CREATE OR REPLACE FUNCTION omp_control.install_workspace_rls(target regclass, workspace_column name) RETURNS void LANGUAGE plpgsql SET search_path = pg_catalog AS $$
DECLARE target_schema text; column_type regtype; nullable bool;
BEGIN
 SELECT n.nspname, a.atttypid::regtype, a.attnotnull INTO target_schema, column_type, nullable FROM pg_class c JOIN pg_namespace n ON n.oid=c.relnamespace JOIN pg_attribute a ON a.attrelid=c.oid AND a.attname=workspace_column AND a.attnum>0 AND NOT a.attisdropped WHERE c.oid=target;
 IF target_schema NOT IN ('omp_control','omp_work','omp_evidence','omp_audit','omp_integration','omp_fleet') THEN RAISE EXCEPTION 'invalid RLS schema'; END IF;
 IF column_type IS DISTINCT FROM 'uuid'::regtype OR nullable IS DISTINCT FROM true THEN RAISE EXCEPTION 'workspace column must be NOT NULL UUID'; END IF;
 EXECUTE format('ALTER TABLE %s ENABLE ROW LEVEL SECURITY', target);
 EXECUTE format('ALTER TABLE %s FORCE ROW LEVEL SECURITY', target);
 EXECUTE format('CREATE POLICY workspace_actor_policy ON %s USING (%I = omp_control.current_workspace_id() AND omp_control.current_actor_id() IS NOT NULL) WITH CHECK (%I = omp_control.current_workspace_id() AND omp_control.current_actor_id() IS NOT NULL)', target, workspace_column, workspace_column);
END $$;

CREATE TABLE omp_control.workspaces (workspace_id uuid PRIMARY KEY, next_alias integer NOT NULL DEFAULT 1 CHECK(next_alias > 0), provenance jsonb NOT NULL DEFAULT '{}'::jsonb, created_at timestamptz NOT NULL DEFAULT clock_timestamp());
CREATE TABLE omp_control.idempotent_commands (workspace_id uuid NOT NULL REFERENCES omp_control.workspaces, operation_id uuid NOT NULL, request_id uuid NOT NULL, correlation_id uuid NOT NULL, command_type text NOT NULL, required_scope text NOT NULL, request_sha256 text NOT NULL CHECK(request_sha256 ~ '^[0-9a-f]{64}$'), state text NOT NULL CHECK(state IN ('executing','applied','rejected','pending_approval')), response jsonb, error jsonb, result_sha256 text CHECK(result_sha256 ~ '^[0-9a-f]{64}$'), attempt_count integer NOT NULL DEFAULT 1 CHECK(attempt_count BETWEEN 1 AND 3), conflict_count integer NOT NULL DEFAULT 0, diagnostics text[] NOT NULL DEFAULT '{}', created_at timestamptz NOT NULL DEFAULT clock_timestamp(), updated_at timestamptz NOT NULL DEFAULT clock_timestamp(), PRIMARY KEY(workspace_id,operation_id), CHECK(cardinality(diagnostics)<=8));
SELECT omp_control.install_workspace_rls('omp_control.idempotent_commands'::regclass, 'workspace_id');

CREATE TABLE omp_work.work_items (work_id uuid PRIMARY KEY, workspace_id uuid NOT NULL REFERENCES omp_control.workspaces, state text NOT NULL, current_revision_id uuid, current_candidate_id uuid, archived bool NOT NULL DEFAULT false, row_version integer NOT NULL DEFAULT 1, provenance jsonb NOT NULL DEFAULT '{}'::jsonb, created_at timestamptz NOT NULL DEFAULT clock_timestamp(), UNIQUE(workspace_id,work_id));
CREATE TABLE omp_work.work_aliases (work_id uuid NOT NULL REFERENCES omp_work.work_items, workspace_id uuid NOT NULL, key text NOT NULL CHECK(key ~ '^(HOME|OMP)-[1-9][0-9]*$'), primary_alias bool NOT NULL DEFAULT true, origin text NOT NULL CHECK(origin IN ('imported','local')), created_at timestamptz NOT NULL DEFAULT clock_timestamp(), PRIMARY KEY(work_id,key), UNIQUE(workspace_id,key));
CREATE TABLE omp_work.work_revisions (revision_id uuid PRIMARY KEY, work_id uuid NOT NULL REFERENCES omp_work.work_items, workspace_id uuid NOT NULL, revision_number integer NOT NULL CHECK(revision_number>0), title text NOT NULL, description text NOT NULL, scope text NOT NULL, content_sha256 text NOT NULL CHECK(content_sha256 ~ '^[0-9a-f]{64}$'), created_by text NOT NULL, supplied_at timestamptz NOT NULL, recorded_at timestamptz NOT NULL DEFAULT clock_timestamp(), UNIQUE(work_id,revision_number), UNIQUE(work_id,content_sha256));
ALTER TABLE omp_work.work_items ADD CONSTRAINT work_items_revision_fk FOREIGN KEY(current_revision_id) REFERENCES omp_work.work_revisions DEFERRABLE INITIALLY DEFERRED;
CREATE TABLE omp_work.acceptance_criteria (revision_id uuid NOT NULL REFERENCES omp_work.work_revisions, workspace_id uuid NOT NULL, position integer NOT NULL CHECK(position>=0), criterion text NOT NULL, PRIMARY KEY(revision_id,position));
CREATE TABLE omp_work.work_relations (relation_id uuid PRIMARY KEY, workspace_id uuid NOT NULL, source_work_id uuid NOT NULL, target_work_id uuid NOT NULL, kind text NOT NULL CHECK(kind IN ('parent','blocks','duplicate_of','related')), active bool NOT NULL DEFAULT true, revoked_at timestamptz, created_at timestamptz NOT NULL DEFAULT clock_timestamp(), CHECK(source_work_id<>target_work_id), FOREIGN KEY(workspace_id,source_work_id) REFERENCES omp_work.work_items(workspace_id,work_id), FOREIGN KEY(workspace_id,target_work_id) REFERENCES omp_work.work_items(workspace_id,work_id));
CREATE UNIQUE INDEX work_relations_active_unique ON omp_work.work_relations(workspace_id,source_work_id,target_work_id,kind) WHERE active;
CREATE UNIQUE INDEX work_relations_parent_target ON omp_work.work_relations(workspace_id,target_work_id) WHERE active AND kind='parent';
CREATE TABLE omp_work.focus_slots (workspace_id uuid NOT NULL, owner_id uuid NOT NULL, work_id uuid, version integer NOT NULL DEFAULT 0, PRIMARY KEY(workspace_id,owner_id), FOREIGN KEY(workspace_id,work_id) REFERENCES omp_work.work_items(workspace_id,work_id));
CREATE TABLE omp_work.candidates (candidate_id uuid PRIMARY KEY, workspace_id uuid NOT NULL, work_id uuid NOT NULL, revision_id uuid NOT NULL REFERENCES omp_work.work_revisions, candidate_sha256 text NOT NULL CHECK(candidate_sha256 ~ '^[0-9a-f]{64}$'), commit_sha text, allocated_at timestamptz NOT NULL, UNIQUE(work_id,revision_id,candidate_sha256), FOREIGN KEY(workspace_id,work_id) REFERENCES omp_work.work_items(workspace_id,work_id));
ALTER TABLE omp_work.work_items ADD CONSTRAINT work_items_candidate_fk FOREIGN KEY(current_candidate_id) REFERENCES omp_work.candidates DEFERRABLE INITIALLY DEFERRED;
CREATE TABLE omp_work.project_health (workspace_id uuid NOT NULL, project_id uuid NOT NULL, health text NOT NULL CHECK(health IN ('onTrack','atRisk','offTrack')), updated_at timestamptz NOT NULL DEFAULT clock_timestamp(), PRIMARY KEY(workspace_id,project_id));

CREATE TABLE omp_evidence.receipts (receipt_id uuid PRIMARY KEY, workspace_id uuid NOT NULL, work_id uuid NOT NULL, revision_id uuid NOT NULL, candidate_id uuid NOT NULL, kind text NOT NULL, payload jsonb NOT NULL, payload_sha256 text NOT NULL CHECK(payload_sha256 ~ '^[0-9a-f]{64}$'), issued_at timestamptz NOT NULL, CHECK(octet_length(payload::text)<=1048576), FOREIGN KEY(workspace_id,work_id) REFERENCES omp_work.work_items(workspace_id,work_id), FOREIGN KEY(candidate_id) REFERENCES omp_work.candidates(candidate_id));
CREATE TABLE omp_evidence.closeout_intents (intent_id uuid PRIMARY KEY, workspace_id uuid NOT NULL, work_id uuid NOT NULL, revision_id uuid NOT NULL, candidate_id uuid NOT NULL, state text NOT NULL DEFAULT 'pending' CHECK(state IN ('pending','completed')), requested_at timestamptz NOT NULL DEFAULT clock_timestamp(), completed_at timestamptz, UNIQUE(work_id,revision_id,candidate_id,state));
CREATE TABLE omp_audit.domain_events (event_id uuid PRIMARY KEY, sequence bigserial UNIQUE NOT NULL, workspace_id uuid NOT NULL, aggregate_type text NOT NULL, aggregate_id uuid NOT NULL, aggregate_version integer NOT NULL, actor_id uuid NOT NULL, actor_kind text NOT NULL, capability_id uuid NOT NULL, request_id uuid NOT NULL, correlation_id uuid NOT NULL, operation_id uuid NOT NULL, event_type text NOT NULL, outcome text NOT NULL, payload jsonb NOT NULL, payload_sha256 text NOT NULL CHECK(payload_sha256 ~ '^[0-9a-f]{64}$'), previous_event_sha256 text, event_sha256 text NOT NULL CHECK(event_sha256 ~ '^[0-9a-f]{64}$'), occurred_at timestamptz NOT NULL DEFAULT clock_timestamp());
CREATE TABLE omp_integration.external_refs (workspace_id uuid NOT NULL, system text NOT NULL, external_id text NOT NULL, work_id uuid NOT NULL, immutable jsonb NOT NULL DEFAULT '{}'::jsonb, created_at timestamptz NOT NULL DEFAULT clock_timestamp(), PRIMARY KEY(workspace_id,system,external_id));

SELECT omp_control.install_workspace_rls('omp_work.work_items'::regclass, 'workspace_id'); SELECT omp_control.install_workspace_rls('omp_work.work_aliases'::regclass, 'workspace_id'); SELECT omp_control.install_workspace_rls('omp_work.work_revisions'::regclass, 'workspace_id'); SELECT omp_control.install_workspace_rls('omp_work.acceptance_criteria'::regclass, 'workspace_id'); SELECT omp_control.install_workspace_rls('omp_work.work_relations'::regclass, 'workspace_id'); SELECT omp_control.install_workspace_rls('omp_work.focus_slots'::regclass, 'workspace_id'); SELECT omp_control.install_workspace_rls('omp_work.candidates'::regclass, 'workspace_id'); SELECT omp_control.install_workspace_rls('omp_work.project_health'::regclass, 'workspace_id'); SELECT omp_control.install_workspace_rls('omp_evidence.receipts'::regclass, 'workspace_id'); SELECT omp_control.install_workspace_rls('omp_evidence.closeout_intents'::regclass, 'workspace_id'); SELECT omp_control.install_workspace_rls('omp_audit.domain_events'::regclass, 'workspace_id'); SELECT omp_control.install_workspace_rls('omp_integration.external_refs'::regclass, 'workspace_id');

CREATE OR REPLACE FUNCTION omp_control.reject_immutable() RETURNS trigger LANGUAGE plpgsql SET search_path=pg_catalog AS $$ BEGIN RAISE EXCEPTION 'immutable history'; END $$;
CREATE TRIGGER immutable_aliases BEFORE UPDATE OR DELETE ON omp_work.work_aliases FOR EACH ROW EXECUTE FUNCTION omp_control.reject_immutable();
CREATE TRIGGER immutable_revisions BEFORE UPDATE OR DELETE ON omp_work.work_revisions FOR EACH ROW EXECUTE FUNCTION omp_control.reject_immutable();
CREATE TRIGGER immutable_criteria BEFORE UPDATE OR DELETE ON omp_work.acceptance_criteria FOR EACH ROW EXECUTE FUNCTION omp_control.reject_immutable();
CREATE TRIGGER immutable_candidates BEFORE UPDATE OR DELETE ON omp_work.candidates FOR EACH ROW EXECUTE FUNCTION omp_control.reject_immutable();
CREATE TRIGGER immutable_receipts BEFORE UPDATE OR DELETE ON omp_evidence.receipts FOR EACH ROW EXECUTE FUNCTION omp_control.reject_immutable();
CREATE TRIGGER immutable_events BEFORE UPDATE OR DELETE ON omp_audit.domain_events FOR EACH ROW EXECUTE FUNCTION omp_control.reject_immutable();
CREATE TRIGGER immutable_refs BEFORE UPDATE OR DELETE ON omp_integration.external_refs FOR EACH ROW EXECUTE FUNCTION omp_control.reject_immutable();
GRANT SELECT,INSERT,UPDATE ON ALL TABLES IN SCHEMA omp_control,omp_work,omp_evidence,omp_audit,omp_integration TO omp_work_app;
GRANT SELECT ON ALL TABLES IN SCHEMA omp_control,omp_work,omp_evidence,omp_audit,omp_integration TO omp_work_readonly;
REVOKE DELETE,TRUNCATE ON ALL TABLES IN SCHEMA omp_control,omp_work,omp_evidence,omp_audit,omp_integration FROM omp_work_app,omp_work_readonly;
